import { expectArray, expectRecord, expectString, requestApi, expectReceipt, type ApiRequestBody } from '@/lib/api/client'

export type DocumentState = 'pending_upload' | 'quarantined' | 'scanning' | 'available' | 'rejected' | 'scan_failed' | 'pending_delete' | 'deleted'
export interface DocumentDto { readonly id: string; readonly purpose: string; readonly version_id: string; readonly state: DocumentState; readonly scan_result: 'clean' | 'malicious' | 'failed' | null; readonly lifecycle: 'active' | 'pending_delete' | 'deleted'; readonly allowed_actions: readonly string[]; readonly record_version: number; readonly updated_at: string }
function decodeDocument(value: unknown): DocumentDto { const row = expectRecord(value); const state = expectString(row.state) as DocumentState; return { id: expectString(row.id), purpose: expectString(row.purpose), version_id: expectString(row.version_id ?? row.versionId), state, scan_result: typeof row.scan_result === 'string' ? row.scan_result as DocumentDto['scan_result'] : null, lifecycle: (typeof row.lifecycle === 'string' ? row.lifecycle : 'active') as DocumentDto['lifecycle'], allowed_actions: Array.isArray(row.allowed_actions) ? row.allowed_actions.filter((x): x is string => typeof x === 'string') : [], record_version: Number(row.record_version ?? 0), updated_at: expectString(row.updated_at ?? row.updatedAt) } }
export function listDocuments(query = '') { const suffix = query ? `?${query}` : ''; return requestApi({ path: `/api/v1/documents${suffix}` as `/${string}` }, (value) => { const root = expectRecord(value); return expectArray(root.items ?? root.documents, decodeDocument) }) }
export function listCaseDocuments(caseId: string) { return requestApi({ path: `/api/v1/cases/${encodeURIComponent(caseId)}/documents` as `/${string}` }, (value) => { const root = expectRecord(value); return expectArray(root.items ?? root.documents, decodeDocument) }) }
export function createUploadSession(caseId: string, body: ApiRequestBody) { return requestApi({ path: `/api/v1/cases/${encodeURIComponent(caseId)}/documents/upload-intents`, method: 'POST', body, idempotencyKey: crypto.randomUUID() }, expectReceipt) }
export function documentCommand(caseId: string, documentId: string, action: 'deletions' | 'restorations', body: ApiRequestBody, expectedRecordVersion: number) { return requestApi({ path: `/api/v1/cases/${encodeURIComponent(caseId)}/documents/${encodeURIComponent(documentId)}/${action}` as `/${string}`, method: 'POST', body, idempotencyKey: crypto.randomUUID(), expectedRecordVersion }, expectReceipt) }
export function requestDocumentDownload(caseId: string, documentId: string, versionId: string) { return requestApi({ path: `/api/v1/cases/${encodeURIComponent(caseId)}/documents/${encodeURIComponent(documentId)}/download-intents`, method: 'POST', body: { version_id: versionId }, idempotencyKey: crypto.randomUUID(), responseMode: 'raw' }, (value) => expectRecord(value)) }
