import "server-only";
import { createHmac, timingSafeEqual } from "node:crypto";
import { findDuplicateWarnings, normalizeDisplayName, normalizeEmail, normalizePhone } from "../domain/approved-p2-contract.ts";
import type { PotentialDuplicateKind, PotentialDuplicateTokenPayload } from "../domain/potential-duplicate-warning.ts";
export interface PotentialDuplicateWarningCandidate { readonly id:string; readonly displayName:string|null; readonly email:string|null; readonly phone:string|null }
const secret=process.env.TIANXING_DUPLICATE_WARNING_SECRET ?? (process.env.AUTH_MODE === "database-test" || process.env.NODE_ENV !== "production" ? "local-synthetic-duplicate-warning-secret" : null);
function requireSecret(){if(!secret)throw new Error("Duplicate warning codec unavailable.");return secret;}
function hash(v:string){return createHmac("sha256",requireSecret()).update(v).digest("hex");}
function signRaw(v:string){return createHmac("sha256",requireSecret()).update(v).digest("base64url");}
function sign(p:PotentialDuplicateTokenPayload){const body=Buffer.from(JSON.stringify(p)).toString("base64url");return `${body}.${signRaw(body)}`;}
export function buildPotentialDuplicateWarnings(input:{kind:PotentialDuplicateKind;name:string|null;email:string|null;phone:string|null;candidates:readonly PotentialDuplicateWarningCandidate[];organizationId:string;actorUserId:string;candidateVersion:string;nowMs?:number}){const now=input.nowMs??Date.now();const normalized={name:normalizeDisplayName(input.name),email:normalizeEmail(input.email),phone:normalizePhone(input.phone)};const matches=findDuplicateWarnings({displayName:normalized.name,email:normalized.email,phone:normalized.phone},input.candidates);const warnings=Object.freeze(matches.map(m=>{const c=input.candidates.find(x=>x.id===m.id)!;return Object.freeze({id:c.id,matchingFields:m.matchingFields,displayNameHint:c.displayName,emailHint:c.email,phoneHint:c.phone});}));const fieldsHash=hash(JSON.stringify(normalized));return Object.freeze({warnings,warningToken:warnings.length?sign({org:input.organizationId,actor:input.actorUserId,kind:input.kind,fieldsHash,candidateVersion:input.candidateVersion,expiresAt:now+600000}):null,fieldsHash});}
export function verifyPotentialDuplicateWarningToken(token:string,expected:Pick<PotentialDuplicateTokenPayload,"org"|"actor"|"kind"|"fieldsHash"|"candidateVersion">,now=Date.now()){try{const [body,sig]=token.split(".");if(!body||!sig)return false;const actual=signRaw(body);if(Buffer.byteLength(sig)!==Buffer.byteLength(actual)||!timingSafeEqual(Buffer.from(sig),Buffer.from(actual)))return false;const p=JSON.parse(Buffer.from(body,"base64url").toString()) as PotentialDuplicateTokenPayload;return p.org===expected.org&&p.actor===expected.actor&&p.kind===expected.kind&&p.fieldsHash===expected.fieldsHash&&p.candidateVersion===expected.candidateVersion&&p.expiresAt>=now;}catch{return false;}}
export const potentialDuplicateTokenCodec=Object.freeze({issue(input:{organizationId:string;actorUserId:string;kind:PotentialDuplicateKind;name:string|null;email:string|null;phone:string|null;candidateVersion:string;nowMs:number}){const normalized={name:normalizeDisplayName(input.name),email:normalizeEmail(input.email),phone:normalizePhone(input.phone)};return sign({org:input.organizationId,actor:input.actorUserId,kind:input.kind,fieldsHash:hash(JSON.stringify(normalized)),candidateVersion:input.candidateVersion,expiresAt:input.nowMs+600000});}});
export function canonicalPotentialDuplicateFieldsHash(input:{name:string|null;email:string|null;phone:string|null}){return hash(JSON.stringify({name:normalizeDisplayName(input.name),email:normalizeEmail(input.email),phone:normalizePhone(input.phone)}));}
