'use client'

import Link from 'next/link'
import { useCallback, useEffect, useState } from 'react'
import { getCaseF3, completeCaseAction } from '@/components/tasks/f3-client'
import { EmptyState, ErrorState, LoadingState, UnavailableState } from '@/components/states/WorkspaceState'

export function F3CaseSection({ caseId, section }: { readonly caseId: string; readonly section: 'applications' | 'interviews' | 'close' }) { const [data, setData] = useState<Record<string, unknown> | null>(null); const [state, setState] = useState<'loading'|'ready'|'empty'|'unavailable'|'error'>('loading'); const load = useCallback(() => { if (section === 'close') { setState('ready'); return } setState('loading'); void getCaseF3(caseId, section).then((value) => { setData(value); setState(Array.isArray(value.items) && value.items.length ? 'ready' : 'empty') }).catch(() => setState('unavailable')) }, [caseId, section]); useEffect(() => { load() }, [load]); if (state === 'loading') return <LoadingState title="正在载入 Case workspace" />; if (state === 'unavailable') return <UnavailableState title="Cases/SchoolTarget 服务暂时不可用" detail="不会在前端推进 Target 状态或创建 Task。" onRetry={load} />; if (state === 'error') return <ErrorState title="Case workspace 读取失败" onRetry={load} />; if (section === 'close') return <ClosePanel caseId={caseId} />; if (state === 'empty') return <EmptyState title={section === 'interviews' ? '目前没有学校要求面试' : '目前没有可显示的申请 Target'} detail="空结果不代表 denied；请先完成同版名单确认和服务端重验。" />; return <div className="workspace-section"><div className="space-y-2">{(data?.items as readonly Record<string, unknown>[]).map((item, index) => <div className="selection-card" key={String(item.id ?? index)}><span className="min-w-0"><strong>{String(item.school_name ?? item.schoolName ?? '受控 SchoolReferencePin')}</strong><small>Target：{String(item.state ?? 'unknown')} · Task：{String(item.task_state ?? '未创建')}</small></span><span className="status-pill">{Array.isArray(item.allowed_actions) ? item.allowed_actions.join(' · ') : '只读'}</span></div>)}</div></div> }

function ClosePanel({ caseId }: { readonly caseId: string }) { const [notice, setNotice] = useState<string | null>(null); return <section className="workspace-section"><h3 className="section-title">Founder 结案</h3><p className="section-detail">所有学校拒绝时不会自动结案；Founder 必须明确提交，服务端重新验证前置条件。</p><button className="primary-button mt-4" onClick={() => void completeCaseAction(caseId, 'close', { reason: 'founder_case_close' }).then(() => setNotice('结案 receipt 已返回。')).catch(() => setNotice('结案不可用或当前身份被拒绝。'))}>Founder 结案</button>{notice ? <p className="mt-3" role="status">{notice}</p> : null}<Link className="secondary-button mt-4" href={`/cases/${caseId}`}>返回 Case</Link></section> }
