import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import type {APIRequestContext,Page,Response} from 'playwright-core';
import type {Client} from 'pg';
export async function assertTrialGuardianHttp(input:{page:Page;request:APIRequestContext;baseUrl:string;client:Client;studentId:string;guardianId:string}){
  const {page,request,baseUrl,client,studentId,guardianId}=input;
  const otherId=randomUUID();
  await client.query(`INSERT INTO crm_guardians(id,organization_id,display_name,email,status)
    SELECT $1,organization_id,'Trial HTTP Additional Guardian','additional@example.invalid','active' FROM crm_students WHERE id=$2`,[otherId,studentId]);
  const root=`${baseUrl}/api/v1/students/${studentId}`;
  const search=await request.post(`${root}/guardians/search`,{data:{query:'Trial HTTP Additional'}});
  assert.equal(search.status(),200);
  assert.ok((await search.json()).data.some((row:{id:string})=>row.id===otherId));
  const attachData={guardian_id:otherId,relationship_type:'mother',relationship_description:null,is_legal_guardian:false,is_emergency_contact:true,is_billing_contact:false,notification_consent:false};
  await page.goto(`${baseUrl}/students/${studentId}/guardians`);
  await page.getByLabel('搜尋姓名、電郵或電話').fill('Trial HTTP Additional');
  await page.getByRole('button',{name:'搜尋監護人',exact:true}).click();
  await page.getByRole('radio').check();
  await page.getByRole('combobox',{name:'關係類型',exact:true}).selectOption('mother');
  await page.getByLabel('緊急聯絡人',{exact:true}).check();
  let uncertainKey:string|undefined;
  await page.route(`${root}/guardians`,async route=>{
    if(route.request().method()!=='POST'||uncertainKey){await route.continue();return;}
    uncertainKey=route.request().headers()['idempotency-key'];
    const committed=await route.fetch();assert.equal(committed.status(),201);
    await route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({api_version:'v1',request_id:'synthetic-lost-ack',error:{code:'SERVICE_UNAVAILABLE',message:'Retry',retryable:true}})});
  });
  await page.getByRole('button',{name:'確認關聯',exact:true}).click();
  await page.getByText('服務暫時不可用。可保留原內容重試，系統不會重複處理。',{exact:true}).waitFor();
  const refreshResponses:{endpoint:string;status:number}[]=[];
  const captureRefresh=(response:Response)=>{
    if(response.request().method()!=='GET')return;
    const endpoints=[[`${root}/guardians`,'relationships'],[root,'student'],[`${baseUrl}/api/v1/auth/me`,'access']];
    const endpoint=endpoints.find(([url])=>url===response.url())?.[1];
    if(endpoint)refreshResponses.push({endpoint,status:response.status()});
  };
  page.on('response',captureRefresh);
  const attachResponse=page.waitForResponse(response=>response.url()===`${root}/guardians`&&response.request().method()==='POST');
  await page.getByRole('button',{name:'確認關聯',exact:true}).click();
  const attached=await attachResponse;
  assert.equal(attached.status(),201);
  const attachHeaders={'idempotency-key':attached.request().headers()['idempotency-key']!};
  assert.equal(attachHeaders['idempotency-key'],uncertainKey,'uncertain response retries preserve the original key');
  await page.unroute(`${root}/guardians`);
  const attachReceipt=(await attached.json()).data;
  try{await page.getByText('監護人已關聯。',{exact:true}).waitFor();}
  catch(error){
    process.stdout.write(JSON.stringify({trial_guardian_refresh_failure:refreshResponses})+'\n');
    await page.screenshot({path:'/tmp/access-trial-guardian-refresh-failure.png',fullPage:true});
    throw error;
  }finally{page.off('response',captureRefresh)}
  const primary=(await client.query('SELECT id,record_version FROM crm_student_guardian_relationships WHERE student_id=$1 AND is_primary_contact AND ends_at IS NULL',[studentId])).rows[0];
  assert.equal((await request.post(`${root}/guardian-relationships/${primary.id}/end`,{headers:{'idempotency-key':`deny-primary-${randomUUID()}`},data:{expected_record_version:Number(primary.record_version)}})).status(),409);
  const handoffData={successor_guardian_id:otherId,expected_primary_record_version:Number(primary.record_version)};
  await page.getByRole('combobox',{name:'新主要聯絡人',exact:true}).selectOption(otherId);
  await page.getByLabel('我確認交接主要聯絡人。',{exact:true}).check();
  const handoffResponse=page.waitForResponse(response=>response.url().endsWith('/guardians/primary-handoffs')&&response.request().method()==='POST');
  await page.getByRole('button',{name:'確認交接',exact:true}).click();
  const handed=await handoffResponse;
  assert.equal(handed.status(),200);
  const handoffHeaders={'idempotency-key':handed.request().headers()['idempotency-key']!};
  const handoffReceipt=(await handed.json()).data;
  await page.getByText('主要聯絡人已交接，原聯絡人仍保留關聯。',{exact:true}).waitFor();
  assert.deepEqual((await (await request.post(`${root}/guardians/primary-handoffs`,{headers:handoffHeaders,data:handoffData})).json()).data,handoffReceipt);
  const current=(await client.query('SELECT id,guardian_id,is_primary_contact,record_version FROM crm_student_guardian_relationships WHERE student_id=$1 AND ends_at IS NULL',[studentId])).rows;
  assert.equal(current.length,2);
  assert.equal(current.find(row=>row.is_primary_contact)?.guardian_id,otherId);
  const former=current.find(row=>row.guardian_id===guardianId)!;
  assert.equal(former.is_primary_contact,false);
  const endData={expected_record_version:Number(former.record_version)};
  await page.getByRole('button',{name:/解除與 .* 的關係/}).click();
  const endResponse=page.waitForResponse(response=>response.url().endsWith(`/guardian-relationships/${former.id}/end`)&&response.request().method()==='POST');
  await page.getByRole('button',{name:'確認解除',exact:true}).click();
  const ended=await endResponse;
  assert.equal(ended.status(),200);
  const endHeaders={'idempotency-key':ended.request().headers()['idempotency-key']!};
  await page.getByText('關係已解除，歷史已保留。',{exact:true}).waitFor();
  assert.deepEqual((await (await request.post(`${root}/guardian-relationships/${former.id}/end`,{headers:endHeaders,data:endData})).json()).data,(await ended.json()).data);
  assert.deepEqual((await (await request.post(`${root}/guardians`,{headers:attachHeaders,data:attachData})).json()).data,attachReceipt);
  const relationships=(await (await request.get(`${root}/guardians`)).json()).data.relationships;
  assert.equal(relationships.length,1);
  assert.equal(relationships[0].guardian.id,otherId);
  await page.reload();
  await page.getByRole('heading',{name:'目前關係',exact:true}).waitFor();
  assert.equal(await page.getByRole('button',{name:/解除與 .* 的關係/}).count(),0);
  await page.setViewportSize({width:390,height:844});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);
  await page.screenshot({path:'/tmp/access-trial-guardian-ui-mobile.png',fullPage:true});
  const newBody={...attachData,guardian:{display_name:`Synthetic created guardian ${randomUUID()}`,email:`new-${randomUUID()}@example.invalid`,phone:null,date_of_birth:null,gender:null,warning_token:null}};
  const {guardian_id:existingId,...newRequest}=newBody;void existingId;
  await page.getByLabel('新監護人姓名',{exact:true}).fill(newBody.guardian.display_name);
  await page.getByLabel('新監護人電郵',{exact:true}).fill(newBody.guardian.email);
  await page.getByRole('combobox',{name:'新監護人關係類型',exact:true}).selectOption('mother');
  await page.getByLabel('新監護人是緊急聯絡人',{exact:true}).check();
  const newResponse=page.waitForResponse(response=>response.url()===`${root}/guardians/new`&&response.request().method()==='POST');
  await page.getByRole('button',{name:'建立並關聯監護人',exact:true}).click();
  const newResult=await newResponse;
  assert.equal(newResult.status(),201);
  const newHeaders={'idempotency-key':newResult.request().headers()['idempotency-key']!};
  await page.getByText('新監護人已建立並關聯，主要聯絡人未變更。',{exact:true}).waitFor();
  const newReceipt=(await newResult.json()).data;
  assert.equal(newReceipt.relationship.is_primary_contact,false);
  assert.deepEqual((await (await request.post(`${root}/guardians/new`,{headers:newHeaders,data:newRequest})).json()).data,newReceipt);
  assert.equal((await request.post(`${root}/guardians/new`,{headers:{'idempotency-key':`duplicate-${randomUUID()}`},data:newRequest})).status(),409);
  await page.getByLabel('新監護人姓名',{exact:true}).fill(newBody.guardian.display_name);
  await page.getByLabel('新監護人電郵',{exact:true}).fill(newBody.guardian.email);
  await page.getByRole('button',{name:'建立並關聯監護人',exact:true}).click();
  await page.getByText('發現疑似重複監護人',{exact:true}).waitFor();
  assert.equal(await page.getByRole('button',{name:'建立並關聯監護人',exact:true}).isDisabled(),true);
  await page.getByLabel('我已核對，仍要建立另一名監護人。',{exact:true}).check();
  const duplicateCreated=page.waitForResponse(response=>response.url()===`${root}/guardians/new`&&response.request().method()==='POST');
  await page.getByRole('button',{name:'建立並關聯監護人',exact:true}).click();
  assert.equal((await duplicateCreated).status(),201);
  await page.getByText('新監護人已建立並關聯，主要聯絡人未變更。',{exact:true}).waitFor();
  await page.reload();
  await page.getByRole('heading',{name:'新建監護人並關聯',exact:true}).waitFor();
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);
  await page.screenshot({path:'/tmp/access-trial-new-guardian-ui-mobile.png',fullPage:true});
  const warning=await request.post(`${baseUrl}/api/v1/crm/potential-duplicates`,{data:{kind:'guardian',name:newBody.guardian.display_name,email:newBody.guardian.email,phone:null}});
  assert.equal(warning.status(),200);
  const warningData=(await warning.json()).data;
  assert.ok(warningData.warning_token);
  const acknowledged=await request.post(`${root}/guardians/new`,{headers:{'idempotency-key':`acknowledged-${randomUUID()}`},data:{...newRequest,guardian:{...newRequest.guardian,warning_token:warningData.warning_token}}});
  assert.equal(acknowledged.status(),201);
  assert.notEqual((await acknowledged.json()).data.relationship.guardian_id,newReceipt.relationship.guardian_id);
  assert.equal((await request.post(`${root}/guardians/new`,{headers:{'idempotency-key':`invalid-${randomUUID()}`},data:{...newRequest,guardian:{...newRequest.guardian,email:null,phone:null}}})).status(),422);
  assert.equal((await request.post(`${root}/guardians/new`,{headers:{'idempotency-key':`identity-${randomUUID()}`},data:{...newRequest,guardian_id:otherId}})).status(),400);
  process.stdout.write(JSON.stringify({trial_guardian_http:'pass',l1:'ui_search_attach_handoff_end_reload',former_primary:'retained_until_explicit_end',replay:'original_receipts'})+'\n');
}
