import type { AdmissionRecord } from '@/types/index'

export const mockSchools: AdmissionRecord[] = [
  {
    school_key: 'YCH_TUNG_CHI_YING_MEM_SEC_SCHOOL',
    school_name_zh: '仁濟醫院董之英紀念中學',
    school_name_en: 'YCH Tung Chi Ying Memorial Secondary School',
    website: 'https://www.ychtymssc.edu.hk',
    final_admission_url: 'https://www.ychtymssc.edu.hk/index.php?id=202526admission',
    admission_type: 'transfer',
    confidence: 'high',
    application_dates: '2025-10-01 to 2025-11-30',
    required_materials: '申請表、成績單、推薦信、學生手冊',
    application_form_links: ['https://www.ychtymssc.edu.hk/application-form'],
    evidence_urls: [],
    review_status: 'approved',
    notes: '202526 入學申請，插班生專頁',
    district: '葵青區',
  },
  {
    school_key: 'YCH_WONG_WHA_SAN_SECONDARY_SCHOOL',
    school_name_zh: '仁濟醫院王華湘中學',
    school_name_en: 'YCH Wong Wha San Secondary School',
    website: 'https://www.ychwwsss.edu.hk',
    final_admission_url: 'https://www.ychwwsss.edu.hk/index.php?wid=15',
    admission_type: 'transfer',
    confidence: 'high',
    application_dates: '2025-10-15 to 2025-12-15',
    required_materials: 'Application-for-Admission 表單、成績單',
    application_form_links: ['https://www.ychwwsss.edu.hk/application'],
    evidence_urls: [],
    review_status: 'approved',
    notes: 'wid=15 轉校專頁',
    district: '荃灣區',
  },
  {
    school_key: 'YPI_CA_LEE_LIM_MING_COLLEGE',
    school_name_zh: '恩平工商會李琳明中學',
    school_name_en: 'Enping Gongshang Lee Lim Ming College',
    website: 'https://www.eplmc.edu.hk',
    final_admission_url: 'https://forms.gle/784U5PzYoT8K6Xed9',
    admission_type: 'transfer',
    confidence: 'medium',
    application_dates: '待確認',
    required_materials: '網上申請表',
    application_form_links: ['https://forms.gle/784U5PzYoT8K6Xed9'],
    evidence_urls: [],
    review_status: 'needs_review',
    notes: 'React SPA，Google Form 直鏈',
    district: '元朗區',
  },
  {
    school_key: 'BUDDHIST_TAI_HUNG_COLLEGE',
    school_name_zh: '佛教大雄中學',
    school_name_en: 'Buddhist Tai Hung College',
    website: 'https://www.bthc.edu.hk',
    final_admission_url: 'https://www.bthc.edu.hk/admission',
    admission_type: 'transfer',
    confidence: 'high',
    application_dates: '2025-11-01 to 2026-01-31',
    required_materials: '申請表、成績副本、在學證明',
    application_form_links: [],
    evidence_urls: [],
    review_status: 'approved',
    notes: '插班/轉校招生，已修正 admit_type',
    district: '觀塘區',
  },
  {
    school_key: 'YU_CHUN_KEUNG_MEMORIAL_COLLEGE_NO_2',
    school_name_zh: '余振強紀念第二中學',
    school_name_en: 'Yu Chun Keung Memorial College No. 2',
    website: 'https://www.yckmc2.edu.hk',
    final_admission_url: 'https://www.yckmc2.edu.hk/25-26-admissions',
    admission_type: 'transfer',
    confidence: 'high',
    application_dates: '2025-10-01 to 2025-12-31',
    required_materials: '網上申請表、PDF 附件',
    application_form_links: [],
    evidence_urls: [],
    review_status: 'approved',
    notes: 'Wix 大頁面，/25-26-admissions + PDF',
    district: '深水埗區',
  },
  {
    school_key: 'YING_WA_GIRLS_SCHOOL',
    school_name_zh: '英華女學校',
    school_name_en: "Ying Wa Girls' School",
    website: 'https://www.ywgs.edu.hk',
    final_admission_url: 'https://www.ywgs.edu.hk/application-admission-s2-and-s3-2026-2027',
    admission_type: 'transfer',
    confidence: 'high',
    application_dates: '2025-09-01 to 2025-11-30',
    required_materials: '申請表、近期成績單、教師推薦信',
    application_form_links: ['https://www.ywgs.edu.hk/application-form-s2-s3'],
    evidence_urls: [],
    review_status: 'approved',
    notes: 'S2/S3 插班，2026-2027',
    district: '油尖旺區',
  },
  {
    school_key: 'HK_PEIHUA_EDU_FOUNDATION_SEC',
    school_name_zh: '香港培華教育基金會中學',
    school_name_en: 'HK Peihua Education Foundation Secondary School',
    website: 'https://www.hkpefs.edu.hk',
    final_admission_url: 'https://www.hkpefs.edu.hk/admissions',
    admission_type: 's1_admission',
    confidence: 'medium',
    application_dates: '2026-01-01 to 2026-03-31',
    required_materials: '網上申請、學能測驗成績',
    application_form_links: [],
    evidence_urls: [],
    review_status: 'needs_review',
    notes: 'S1 統一派位',
    district: '沙田區',
  },
  {
    school_key: 'HKU_SCHOOL_OF_PROF_CONT_EDU',
    school_name_zh: '東華三院呂潤財紀念中學',
    school_name_en: 'TWGHs Lui Yun Choy Memorial College',
    website: 'https://www.twghlyc.edu.hk',
    final_admission_url: 'https://www.twghlyc.edu.hk/transfer-admission',
    admission_type: 'transfer',
    confidence: 'low',
    application_dates: '待更新',
    required_materials: '申請表（未確認）',
    application_form_links: [],
    evidence_urls: [],
    review_status: 'needs_review',
    notes: '低信心，需人工核查',
    district: '元朗區',
  },
  {
    school_key: 'ST_PAULS_COLLEGE',
    school_name_zh: '聖保羅書院',
    school_name_en: "St. Paul's College",
    website: 'https://www.spc.edu.hk',
    final_admission_url: 'https://www.spc.edu.hk/admission',
    admission_type: 'transfer',
    confidence: 'high',
    application_dates: '2025-10-01 to 2025-12-31',
    required_materials: '申請表、成績單、推薦信、校長推薦',
    application_form_links: ['https://www.spc.edu.hk/admission-form'],
    evidence_urls: [],
    review_status: 'approved',
    notes: '著名英文中學，轉校競爭激烈',
    district: '中西區',
  },
  {
    school_key: 'DIOCESAN_GIRLS_SCHOOL',
    school_name_zh: '拔萃女書院',
    school_name_en: "Diocesan Girls' School",
    website: 'https://www.dgs.edu.hk',
    final_admission_url: 'https://www.dgs.edu.hk/admissions/transfer',
    admission_type: 'transfer',
    confidence: 'medium',
    application_dates: '2025-11-01 to 2026-01-31',
    required_materials: '申請表、成績單、英文語文能力証明',
    application_form_links: [],
    evidence_urls: [],
    review_status: 'needs_review',
    notes: '傳統名校，收生資訊需定期核查',
    district: '九龍城區',
  },
]
