import type { CaseRecord } from '../../../types/index.ts'

export const mockCases: CaseRecord[] = [
  {
    id: 'CASE-001',
    case_number: 'HK26-0001',
    student_id: 'STU-001',
    student_name: '陳家豪',
    student_name_en: 'Chan Ka Ho',
    application_type: 'k12',
    intake_year: 2026,
    admission_type: 'transfer',
    stage: 'application_submitted',
    stage_label: '已提交申請',
    advisor: '李顧問',
    advisor_role: 'advisor',
    assessment_status: 'selection_ready',
    manifest_status: 'approved',
    blockers: ['推薦信尚未上載'],
    next_action: '跟進推薦信及面試日期',
    next_action_date: '2026-08-12',
    updated_at: '2026-08-04T09:15:00Z',
    school_targets: [
      { id: 'TARGET-001', school_name: '聖保羅書院', admission_type: 'transfer', state: 'submitted', next_action: '等待學校回覆', next_action_date: '2026-08-15', evidence_status: 'complete' },
      { id: 'TARGET-002', school_name: '拔萃女書院', admission_type: 'transfer', state: 'interview', next_action: '準備英文面試', next_action_date: '2026-08-09', evidence_status: 'partial' },
      { id: 'TARGET-003', school_name: '英華女學校', admission_type: 'transfer', state: 'candidate', next_action: '確認申請期限', next_action_date: '2026-08-18', evidence_status: 'missing' },
    ],
    tasks: [
      { id: 'TASK-001', title: '補收推薦信', owner: '李顧問', due_date: '2026-08-08', status: 'blocked' },
      { id: 'TASK-002', title: '準備英文面試題目', owner: '李顧問', due_date: '2026-08-09', status: 'in_progress' },
    ],
    documents: [
      { id: 'DOC-001', name: '申請表', status: 'clean', updated_at: '2026-08-01' },
      { id: 'DOC-002', name: '成績單', status: 'clean', updated_at: '2026-08-01' },
      { id: 'DOC-003', name: '推薦信', status: 'missing', updated_at: '2026-08-04' },
    ],
    activity: [
      { id: 'ACT-001', label: '提交聖保羅書院申請', actor: '李顧問', created_at: '2026-08-04T09:15:00Z', tone: 'success' },
      { id: 'ACT-002', label: '標記推薦信為待補文件', actor: '李顧問', created_at: '2026-08-03T16:20:00Z', tone: 'warning' },
    ],
  },
  {
    id: 'CASE-002',
    case_number: 'HK26-0002',
    student_id: 'STU-002',
    student_name: '林小雯',
    student_name_en: 'Lam Siu Man',
    application_type: 'k12',
    intake_year: 2026,
    admission_type: 'transfer',
    stage: 'interview_preparation',
    stage_label: '面試準備',
    advisor: '王顧問',
    advisor_role: 'advisor',
    assessment_status: 'background_complete',
    manifest_status: 'approved',
    blockers: [],
    next_action: '完成中英文自我介紹練習',
    next_action_date: '2026-08-11',
    updated_at: '2026-08-03T14:40:00Z',
    school_targets: [
      { id: 'TARGET-004', school_name: '仁濟醫院董之英紀念中學', admission_type: 'transfer', state: 'interview', next_action: '準備面試', next_action_date: '2026-08-11', evidence_status: 'complete' },
      { id: 'TARGET-005', school_name: '佛教大雄中學', admission_type: 'transfer', state: 'preparing', next_action: '整理申請文件', next_action_date: '2026-08-20', evidence_status: 'partial' },
    ],
    tasks: [
      { id: 'TASK-003', title: '中英文面試練習', owner: '王顧問', due_date: '2026-08-11', status: 'todo' },
    ],
    documents: [
      { id: 'DOC-004', name: '申請表', status: 'clean', updated_at: '2026-07-29' },
      { id: 'DOC-005', name: '成績單', status: 'clean', updated_at: '2026-07-29' },
      { id: 'DOC-006', name: '推薦信', status: 'clean', updated_at: '2026-07-30' },
    ],
    activity: [
      { id: 'ACT-003', label: '更新面試準備清單', actor: '王顧問', created_at: '2026-08-03T14:40:00Z', tone: 'neutral' },
    ],
  },
  {
    id: 'CASE-003',
    case_number: 'HK26-0003',
    student_id: 'STU-003',
    student_name: '張浩然',
    student_name_en: 'Cheung Ho Yin',
    application_type: 'k12',
    intake_year: 2026,
    admission_type: 's1_admission',
    stage: 'background_collection',
    stage_label: '收集背景資料',
    advisor: '李顧問',
    advisor_role: 'advisor',
    assessment_status: 'draft',
    manifest_status: 'approved',
    blockers: ['英文能力資料未完成', '未確認學校系統'],
    next_action: '完成背景 assessment',
    next_action_date: '2026-08-14',
    updated_at: '2026-08-02T11:05:00Z',
    school_targets: [
      { id: 'TARGET-006', school_name: '香港培華教育基金會中學', admission_type: 's1_admission', state: 'candidate', next_action: '待 assessment 完成', next_action_date: '2026-08-14', evidence_status: 'missing' },
    ],
    tasks: [
      { id: 'TASK-004', title: '收集英文能力資料', owner: '李顧問', due_date: '2026-08-14', status: 'todo' },
    ],
    documents: [
      { id: 'DOC-007', name: '成績單', status: 'clean', updated_at: '2026-07-31' },
      { id: 'DOC-008', name: '學能測驗成績', status: 'missing', updated_at: '2026-08-02' },
    ],
    activity: [
      { id: 'ACT-004', label: '建立 K12 ServiceCase', actor: '李顧問', created_at: '2026-08-02T11:05:00Z', tone: 'neutral' },
    ],
  },
  {
    id: 'CASE-004',
    case_number: 'HK25-0004',
    student_id: 'STU-004',
    student_name: '黃美琪',
    student_name_en: 'Wong Mei Ki',
    application_type: 'k12',
    intake_year: 2025,
    admission_type: 'transfer',
    stage: 'offer_confirmed',
    stage_label: 'Offer 已確認',
    advisor: '陳顧問',
    advisor_role: 'advisor',
    assessment_status: 'selection_ready',
    manifest_status: 'approved',
    blockers: [],
    next_action: '跟進正式入學手續',
    next_action_date: '2026-08-22',
    updated_at: '2026-07-30T10:10:00Z',
    school_targets: [
      { id: 'TARGET-007', school_name: '仁濟醫院王華湘中學', admission_type: 'transfer', state: 'accepted', next_action: '確認註冊文件', next_action_date: '2026-08-22', evidence_status: 'complete' },
    ],
    tasks: [
      { id: 'TASK-005', title: '收集註冊文件', owner: '陳顧問', due_date: '2026-08-22', status: 'in_progress' },
    ],
    documents: [
      { id: 'DOC-009', name: 'Offer Letter', status: 'clean', updated_at: '2026-07-30' },
      { id: 'DOC-010', name: '學生手冊副本', status: 'missing', updated_at: '2026-07-30' },
    ],
    activity: [
      { id: 'ACT-005', label: '記錄 Offer 已接受', actor: '陳顧問', created_at: '2026-07-30T10:10:00Z', tone: 'success' },
    ],
  },
]

export const caseStageLabels: Record<CaseRecord['stage'], string> = {
  signed: '已簽約',
  background_collection: '收集背景資料',
  school_selection_confirmed: '已確認選校',
  interview_preparation: '面試準備',
  application_submitted: '已提交申請',
  awaiting_result: '等待結果',
  offer_confirmed: 'Offer 已確認',
  closed: '已結案',
}
