import assert from "node:assert/strict";
import test from "node:test";
import { PostgresqlStudentCreateRepository } from "../../../modules/crm/infrastructure/postgresql-student-create-repository.ts";
import { StudentCreateRepositoryError,type StudentCreateRepository } from "../../../modules/crm/application/student-create-service.ts";
import type { TenantTransactionRunner } from "../../../modules/shared/server.ts";
import type { TenantDatabaseContext, TenantTransaction } from "../../../modules/shared/server.ts";
import type { MutationEffectBundle } from "../../../modules/audit/public.ts";
import { hashRequestPayload } from "../../../modules/shared/public.ts";
import { potentialDuplicateTokenCodec } from "../../../modules/crm/infrastructure/potential-duplicate-token-codec.ts";
const I={organization:"62000000-0000-4000-8000-000000000001",actor:"62000000-0000-4000-8000-000000000002",student:"62000000-0000-4000-8000-000000000003",guardian:"62000000-0000-4000-8000-000000000004",relationship:"62000000-0000-4000-8000-000000000005"};
const receipt={student:{id:I.student,recordVersion:1},primaryGuardian:{id:I.guardian,recordVersion:1},relationship:{id:I.relationship,recordVersion:1}};
test("new create",async()=>{const r=new PostgresqlStudentCreateRepository(runner(async(_c,q)=>q(async(t)=>{if(t.includes("identity_users"))return out([{binding_id:"x"}]);if(t.includes("pg_try"))return out([{acquired:true}]);if(t.includes("FROM shared_idempotency_records"))return out([]);if(t.includes("INSERT INTO shared_idempotency_records"))return out([{id:"x"}],1);if(t.includes("student_record_version"))return out([{student_id:I.student,student_record_version:1,guardian_id:I.guardian,guardian_record_version:1,relationship_id:I.relationship,relationship_record_version:1}]);if(t.includes("UPDATE shared_idempotency_records"))return out([{id:"62000000-0000-4000-8000-000000000099"}],1);return out([],1)})));assert.deepEqual(await r.createStudent(input()),receipt);});
test("replay",async()=>{const r=new PostgresqlStudentCreateRepository(runner(async(_c,q)=>q(async(t)=>{if(t.includes("identity_users"))return out([{binding_id:"x"}]);if(t.includes("pg_try"))return out([{acquired:true}]);if(t.includes("FROM shared_idempotency_records"))return out([row({state:"completed",result_reference:I.student,response_hash:hashRequestPayload(receipt),record_version:2})]);if(t.includes("student_record_version"))return out([{student_id:I.student,student_record_version:1,guardian_id:I.guardian,guardian_record_version:1,relationship_id:I.relationship,relationship_record_version:1}]);return out([])})));assert.deepEqual(await r.createStudent(input()),receipt);});
test("conflict",async()=>{const r=new PostgresqlStudentCreateRepository(runner(async(_c,q)=>q(async(t)=>{if(t.includes("identity_users"))return out([{binding_id:"x"}]);if(t.includes("pg_try"))return out([{acquired:true}]);if(t.includes("FROM shared_idempotency_records"))return out([row({state:"completed",request_hash:"b".repeat(64),result_reference:I.student,response_hash:hashRequestPayload(receipt),record_version:2})]);return out([])})));await assert.rejects(r.createStudent(input()),(e:any)=>e.code==="STUDENT_CREATE_IDEMPOTENCY_CONFLICT");});
test("unavailable",async()=>{const r=new PostgresqlStudentCreateRepository(runner(async(_c,q)=>q(async(t)=>{if(t.includes("identity_users"))return out([{binding_id:"x"}]);if(t.includes("pg_try"))return out([{acquired:true}]);if(t.includes("FROM shared_idempotency_records"))return out([]);if(t.includes("INSERT INTO shared_idempotency_records"))return out([{id:"x"}],1);if(t.includes("INSERT INTO crm_students"))throw new Error("db");return out([],1)})));await assert.rejects(r.createStudent(input()),(e:any)=>e.code==="STUDENT_CREATE_UNAVAILABLE");});
test("duplicate warning blocks",async()=>{const r=new PostgresqlStudentCreateRepository(runner(async(_c,q)=>q(async(t)=>{if(t.includes("identity_users"))return out([{binding_id:"x"}]);if(t.includes("pg_try"))return out([{acquired:true}]);if(t.includes("FROM shared_idempotency_records"))return out([]);if(t.includes("INSERT INTO shared_idempotency_records"))return out([{id:"x"}],1);if(t.includes("FROM crm_students"))return out([{id:"dup",display_name:"Synthetic Student",email:null,phone:null,record_version:2}]);return out([],1)})));await assert.rejects(r.createStudent(input()),(e:any)=>e.code==="STUDENT_CREATE_DUPLICATE_WARNING_REQUIRED");});
test("valid student and guardian tokens",async()=>{const base=input();assert.equal(base.primaryGuardian.kind,"new");const studentCandidate={id:"62000000-0000-4000-8000-00000000000a",display_name:"Synthetic Student",email:null,phone:null,record_version:2};const guardianCandidate={id:"62000000-0000-4000-8000-00000000000b",display_name:"Synthetic Guardian",email:"guardian@example.invalid",phone:null,record_version:3};const studentToken=potentialDuplicateTokenCodec.issue({organizationId:I.organization,actorUserId:I.actor,kind:"student",name:base.student.displayName,email:base.student.contactEmail,phone:base.student.contactPhone,candidateVersion:`${studentCandidate.id}:2`,nowMs:base.createdAtMs});const guardianToken=potentialDuplicateTokenCodec.issue({organizationId:I.organization,actorUserId:I.actor,kind:"guardian",name:base.primaryGuardian.displayName,email:base.primaryGuardian.email,phone:base.primaryGuardian.phone,candidateVersion:`${guardianCandidate.id}:3`,nowMs:base.createdAtMs});const withTokens={...base,student:{...base.student,warningToken:studentToken},primaryGuardian:{...base.primaryGuardian,warningToken:guardianToken}};const sql:string[]=[];const r=new PostgresqlStudentCreateRepository(runner(async(_c,q)=>q(async(t)=>{sql.push(t);if(t.includes("identity_users"))return out([{binding_id:"x"}]);if(t.includes("pg_try"))return out([{acquired:true}]);if(t.includes("FROM shared_idempotency_records"))return out([]);if(t.includes("INSERT INTO shared_idempotency_records"))return out([{id:"x"}],1);if(t.includes("student_record_version"))return out([{student_id:I.student,student_record_version:1,guardian_id:I.guardian,guardian_record_version:1,relationship_id:I.relationship,relationship_record_version:1}]);if(t.includes("SELECT id,display_name")&&t.includes("FROM crm_students"))return out([studentCandidate]);if(t.includes("SELECT id,display_name")&&t.includes("FROM crm_guardians"))return out([guardianCandidate]);if(t.includes("UPDATE shared_idempotency_records"))return out([{id:"62000000-0000-4000-8000-000000000099"}],1);return out([],1);})));assert.deepEqual(await r.createStudent(withTokens),receipt);const studentIndex=sql.findIndex(x=>x.includes("FROM crm_students"));const guardianIndex=sql.findIndex(x=>x.includes("FROM crm_guardians"));const insertIndex=sql.findIndex(x=>x.includes("INSERT INTO crm_students"));assert.ok(studentIndex>=0&&guardianIndex>=0&&studentIndex<insertIndex&&guardianIndex<insertIndex);assert.ok(sql.some(x=>x.includes("INSERT INTO crm_guardians")));});
function input():Parameters<StudentCreateRepository["createStudent"]>[0]{return {organizationId:I.organization,actorUserId:I.actor,studentId:I.student,guardianId:I.guardian,relationshipId:I.relationship,student:{displayName:"Synthetic Student",dateOfBirth:null,gender:null,contactEmail:null,contactPhone:null,warningToken:null},primaryGuardian:{kind:"new",displayName:"Synthetic Guardian",email:"guardian@example.invalid",phone:null,dateOfBirth:null,gender:null,relationshipType:"father",relationshipDescription:null,isLegalGuardian:true,isEmergencyContact:false,isBillingContact:false,notificationConsent:false,warningToken:null},idempotencyKey:"crm-repository-attempt-1",requestHash:"a".repeat(64),createdAtMs:Date.parse("2026-08-22T08:00:00.000Z"),effects:effects()};}
function effects():MutationEffectBundle{return {audit:{id:I.relationship,organizationId:I.organization,actorUserId:I.actor,actorKind:"user",eventType:"crm.student_primary_guardian_created",eventVersion:1,action:"create",resourceType:"Student",resourceId:I.student,outcome:"succeeded",requestId:"repository-test-request",occurredAt:"2026-08-22T08:00:00.000Z",beforeHashSha256:null,afterHashSha256:null,metadata:{}},outbox:{id:I.guardian,auditEventId:I.relationship,organizationId:I.organization,aggregateType:"Student",aggregateId:I.student,eventType:"crm.student_primary_guardian_created",eventVersion:1,idempotencyKey:"repository-test-outbox",requestId:"repository-test-request",payload:{},status:"pending",attemptCount:0,availableAt:"2026-08-22T08:00:00.000Z",createdAt:"2026-08-22T08:00:00.000Z"}} as MutationEffectBundle;}
function row(o:any={}){return {id:"62000000-0000-4000-8000-000000000099",organization_id:I.organization,actor_kind:"user",actor_opaque_id:I.actor,operation:"crm.create_student_primary_guardian",idempotency_key:"crm-repository-attempt-1",request_hash:"a".repeat(64),state:"in_progress",result_reference:null,response_hash:null,record_version:1,created_at:"2026-08-22T08:00:00.000Z",updated_at:"2026-08-22T08:00:00.000Z",...o};}
function out(rows:any[],rowCount=rows.length){return {rows,rowCount};}
function runner(run:(context:Readonly<{organizationId:string;actorUserId:string}>,queryHarness:(execute:(text:string,values?:readonly unknown[])=>Promise<unknown>)=>Promise<unknown>)=>Promise<unknown>):TenantTransactionRunner{return {async run<Result>(context:TenantDatabaseContext,op:(transaction:TenantTransaction)=>Promise<Result>){return await run(context,async execute=>op({query:({text,values})=>execute(text,values) as never})) as Result;}};}
