import assert from "node:assert/strict";
import test from "node:test";
import { PotentialDuplicateService, PotentialDuplicateError } from "../../../modules/crm/application/potential-duplicate-service.ts";
const actor={userId:"61000000-0000-4000-8000-000000000002",organizationId:"61000000-0000-4000-8000-000000000001",workspaceCapabilities:["students.create"] as const};
function service(rows:any[]=[],codec:any={issue:()=>"opaque"}){let calls=0;const repo={findCandidates:async()=>{calls++;return {candidates:rows,candidateVersion:"a:1"}}};return {s:new PotentialDuplicateService(repo,codec),get calls(){return calls}}}
test("no candidates does not issue token",async()=>{let issued=0;const x=service([], {issue:()=>{issued++;return "x"}});const r=await x.s.check({actor,kind:"student",name:"Alice",email:null,phone:null});assert.deepEqual(r.warnings,[]);assert.equal(r.warningToken,null);assert.equal(issued,0);});
test("matching fields and canonical codec input",async()=>{let got:any;const x=service([{id:"1",displayName:"Other",email:"ALICE@EXAMPLE.INVALID",phone:" 123-456 ",recordVersion:3}],{issue:(v:any)=>{got=v;return "opaque"}});const r=await x.s.check({actor,kind:"student",name:" Alice ",email:"alice@example.invalid",phone:"123456"});assert.deepEqual(r.warnings[0].matchingFields,["email","phone"]);assert.notEqual(r.warnings[0].emailHint,"ALICE@EXAMPLE.INVALID");assert.notEqual(r.warnings[0].phoneHint," 123-456 ");assert.equal(got.candidateVersion,"a:1");});
test("forbidden and empty fail before repository",async()=>{const x=service();await assert.rejects(x.s.check({actor:{...actor,workspaceCapabilities:[]},kind:"student",name:"A",email:null,phone:null}),(e:any)=>e.code==="POTENTIAL_DUPLICATE_FORBIDDEN");assert.equal(x.calls,0);await assert.rejects(x.s.check({actor,kind:"student",name:" ",email:null,phone:null}),(e:any)=>e.code==="POTENTIAL_DUPLICATE_INVALID");assert.equal(x.calls,0);});
test("repository and codec failures are unavailable",async()=>{const repo={findCandidates:async()=>{throw new Error("db")}};const s=new PotentialDuplicateService(repo,{issue:()=>"x"});await assert.rejects(s.check({actor,kind:"student",name:"A",email:null,phone:null}),(e:any)=>e.code==="POTENTIAL_DUPLICATE_UNAVAILABLE");const x=service([{id:"1",displayName:"A",email:null,phone:null,recordVersion:1}],{issue:()=>{throw new Error("codec")}});await assert.rejects(x.s.check({actor,kind:"student",name:"A",email:null,phone:null}),(e:any)=>e.code==="POTENTIAL_DUPLICATE_UNAVAILABLE");});
