'use client'
import Link from 'next/link'
import { useCallback, useEffect, useState } from 'react'
import { listNotifications, markRead, resolveTarget, type NotificationDto } from '@/components/notifications/f4-client'
import { EmptyState, ErrorState, LoadingState, StaleState, UnavailableState } from '@/components/states/WorkspaceState'
import { ApiClientError } from '@/lib/api/client'

const COPY: Record<string, string> = { task_due: '有待處理的任務', task_overdue: '有待處理的任務', case_blocked: '有待處理的案件', candidate_list_review: '有待審核的選校名單', application_update: '有申請資料更新', interview_due: '面試支援任務即將到期', case_close_ready: '案件可以結案', document_scan_ready: '文件已完成檢查', access_changed: '權限已更新' }
export function NotificationsWorkspace() { const [items, setItems] = useState<readonly NotificationDto[]>([]); const [state, setState] = useState<'loading'|'ready'|'empty'|'denied'|'unavailable'|'error'|'stale'>('loading'); const load = useCallback(() => { setState('loading'); void listNotifications().then((value) => { setItems(value); setState(value.length ? 'ready' : 'empty') }).catch((error: unknown) => { if (error instanceof ApiClientError && error.code === 'FORBIDDEN') setState('denied'); else if (error instanceof ApiClientError && error.code === 'SERVICE_UNAVAILABLE') setState('unavailable'); else setState('error') }) }, []); useEffect(() => { load() }, [load]); async function read(item: NotificationDto) { try { await markRead(item.id, item.record_version); setItems((current) => current.map((value) => value.id === item.id ? { ...value, status: 'read', read_at: new Date().toISOString() } : value)) } catch (error) { setState(error instanceof ApiClientError && error.code === 'STALE_VERSION' ? 'stale' : 'error') } } async function open(item: NotificationDto) { try { const route = await resolveTarget(item.id); if (/^\/(?!\/)/.test(route)) window.location.assign(route); else setState('unavailable') } catch { setState('unavailable') } } if (state === 'loading') return <LoadingState title="正在載入通知" />; if (state === 'empty') return <EmptyState title="目前沒有通知" detail="新的提醒會顯示在這裡。" />; if (state === 'denied') return <ErrorState title="無法查看通知" detail="目前帳號沒有查看通知的權限。" />; if (state === 'unavailable') return <UnavailableState title="通知服務暫時不可用" detail="請稍後重試。" onRetry={load} />; if (state === 'stale') return <StaleState title="通知資料已更新" detail="請重新載入後再標記已讀。" onRetry={load} />; if (state === 'error') return <ErrorState title="通知讀取失敗" onRetry={load} />; return <div className="workspace-section space-y-2">{items.map((item) => <article key={item.id} className={`selection-card ${item.status === 'unread' ? 'selected' : ''}`}><span className="min-w-0"><strong>{COPY[item.content_code] ?? '有待處理事項'}</strong><small>{item.created_at}</small></span><span className="flex flex-wrap gap-2">{item.allowed_actions.includes('resolve_target') ? <button className="secondary-button" onClick={() => void open(item)}>開啟</button> : null}{item.status === 'unread' && item.allowed_actions.includes('read') ? <button className="secondary-button" onClick={() => void read(item)}>標記為已讀</button> : null}</span></article>)}</div> }
