'use client'
import Link from 'next/link'
import { useCallback, useEffect, useState } from 'react'
import { listNotifications, markRead, resolveTarget, type NotificationDto } from '@/components/notifications/f4-client'
import { EmptyState, ErrorState, LoadingState, StaleState, UnavailableState } from '@/components/states/WorkspaceState'
import { ApiClientError } from '@/lib/api/client'

const COPY: Record<string, string> = { task_due: '有待办事项需要处理', task_overdue: '有待办事项需要处理', case_blocked: '有待办事项需要处理', candidate_list_review: '有待办事项需要处理', application_update: '有待办事项需要处理', interview_due: '有待办事项需要处理', case_close_ready: '有待办事项需要处理', document_scan_ready: '有待办事项需要处理', access_changed: '有待办事项需要处理' }
export function NotificationsWorkspace() { const [items, setItems] = useState<readonly NotificationDto[]>([]); const [state, setState] = useState<'loading'|'ready'|'empty'|'denied'|'unavailable'|'error'|'stale'>('loading'); const load = useCallback(() => { setState('loading'); void listNotifications().then((value) => { setItems(value); setState(value.length ? 'ready' : 'empty') }).catch((error: unknown) => { if (error instanceof ApiClientError && error.code === 'FORBIDDEN') setState('denied'); else if (error instanceof ApiClientError && error.code === 'SERVICE_UNAVAILABLE') setState('unavailable'); else setState('error') }) }, []); useEffect(() => { load() }, [load]); async function read(item: NotificationDto) { try { await markRead(item.id, item.record_version); setItems((current) => current.map((value) => value.id === item.id ? { ...value, status: 'read', read_at: new Date().toISOString() } : value)) } catch (error) { setState(error instanceof ApiClientError && error.code === 'STALE_VERSION' ? 'stale' : 'error') } } async function open(item: NotificationDto) { try { const route = await resolveTarget(item.id); if (/^\/(?!\/)/.test(route)) window.location.assign(route); else setState('unavailable') } catch { setState('unavailable') } } if (state === 'loading') return <LoadingState title="正在载入通知" />; if (state === 'empty') return <EmptyState title="目前没有通知" detail="新的内部待办提醒会在服务端投影后显示。" />; if (state === 'denied') return <ErrorState title="无法查看通知" detail="当前 Session 没有通知入口权限。" />; if (state === 'unavailable') return <UnavailableState title="通知服务暂时不可用" detail="不会显示旧 unread count 或自行拼接目标路由。" onRetry={load} />; if (state === 'stale') return <StaleState title="通知版本已变化" detail="请重新载入后再标记已读。" onRetry={load} />; if (state === 'error') return <ErrorState title="通知读取失败" onRetry={load} />; return <div className="workspace-section space-y-2">{items.map((item) => <article key={item.id} className={`selection-card ${item.status === 'unread' ? 'selected' : ''}`}><span className="min-w-0"><strong>{COPY[item.content_code] ?? '有待办事项需要处理'}</strong><small>{item.created_at}</small></span><span className="flex flex-wrap gap-2">{item.allowed_actions.includes('resolve_target') ? <button className="secondary-button" onClick={() => void open(item)}>打开</button> : null}{item.status === 'unread' && item.allowed_actions.includes('read') ? <button className="secondary-button" onClick={() => void read(item)}>标为已读</button> : null}</span></article>)}</div> }
