import { hasRequestCapability, type RequestAccessActor } from "../../access/public.ts";
import { findDuplicateWarnings, normalizeDisplayName, normalizeEmail, normalizePhone } from "../domain/approved-p2-contract.ts";
export interface PotentialDuplicateWarningCandidate { readonly id:string; readonly displayName:string|null; readonly email:string|null; readonly phone:string|null; readonly recordVersion:number }
export type PotentialDuplicateKind = "student" | "guardian";
export interface PotentialDuplicateRepository { findCandidates(input: { organizationId: string; actorUserId: string; kind: PotentialDuplicateKind; name: string | null; email: string | null; phone: string | null }): Promise<{ candidates: readonly PotentialDuplicateWarningCandidate[]; candidateVersion: string }> }
export interface PotentialDuplicateTokenCodec { issue(input: { organizationId:string; actorUserId:string; kind:PotentialDuplicateKind; name:string|null; email:string|null; phone:string|null; candidateVersion:string; nowMs:number }): string }
export type PotentialDuplicateErrorCode = "POTENTIAL_DUPLICATE_FORBIDDEN" | "POTENTIAL_DUPLICATE_INVALID" | "POTENTIAL_DUPLICATE_UNAVAILABLE";
export class PotentialDuplicateError extends Error { readonly code: PotentialDuplicateErrorCode; constructor(code: PotentialDuplicateErrorCode){super(code);this.code=code;} }
export class PotentialDuplicateService { private readonly repository: PotentialDuplicateRepository; private readonly codec: PotentialDuplicateTokenCodec; constructor(repository: PotentialDuplicateRepository, codec: PotentialDuplicateTokenCodec) { this.repository=repository; this.codec=codec; }
  async check(input: { actor: RequestAccessActor; kind: PotentialDuplicateKind; name: string; email: string | null; phone: string | null }) { const name=normalizeDisplayName(input.name); const email=normalizeEmail(input.email); const phone=normalizePhone(input.phone); if (!hasRequestCapability(input.actor, "students.create")) throw new PotentialDuplicateError("POTENTIAL_DUPLICATE_FORBIDDEN"); if (!(input.kind === "student" || input.kind === "guardian") || (!name && !email && !phone)) throw new PotentialDuplicateError("POTENTIAL_DUPLICATE_INVALID"); let found; try { found=await this.repository.findCandidates({ organizationId: input.actor.organizationId, actorUserId: input.actor.userId, kind: input.kind, name, email, phone }); } catch { throw new PotentialDuplicateError("POTENTIAL_DUPLICATE_UNAVAILABLE"); } const warnings = found.candidates.flatMap((c) => { const m=findDuplicateWarnings({displayName:name,email,phone},[c])[0]; return m ? [{ id:c.id, matchingFields:m.matchingFields, displayNameHint:c.displayName, emailHint:c.email, phoneHint:c.phone }] : []; }); let warningToken=null; try { if (warnings.length) warningToken=this.codec.issue({ organizationId: input.actor.organizationId, actorUserId: input.actor.userId, kind: input.kind, name, email, phone, candidateVersion: found.candidateVersion, nowMs: Date.now() }); } catch { throw new PotentialDuplicateError("POTENTIAL_DUPLICATE_UNAVAILABLE"); } return { warnings, warningToken, candidateVersion: found.candidateVersion }; }
}
